---------------------------------------------------------------------------
--日常巡查、维修养护初始数据
---------------------------------------------------------------------------

--巡查病害表
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (1, '桥名牌/限载牌', '桥名牌', '桥名牌', '桥名牌', '处', 1, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (2, '桥名牌/限载牌', '限载牌', '限载牌', '限载牌', '处', 1, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (3, '桥面系', '桥面系', '车行道', '碎裂', '处', 1, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (4, '桥面系', '桥面系', '车行道', '局部坑槽', '处', 1, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (5, '桥面系', '桥面系', '车行道', '拥包', '处', 1, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (6, '桥面系', '桥面系', '车行道', '车辙', '处', 1, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (7, '桥面系', '桥面系', '车行道', '桥头跳车', '处', 1, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (8, '桥面系', '桥面系', '车行道', '隔离栏', '处', 1, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (9, '桥面系', '桥面系', '人行道', '板件', '处', 1, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (10, '桥面系', '桥面系', '人行道', '铺装(砖)', '处', 1, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (11, '桥面系', '桥面系', '栏杆', '栏杆扶手', '处', 1, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (12, '桥面系', '桥面系', '栏杆', '栏杆立柱', '处', 1, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (13, '桥面系', '桥面系', '伸缩缝装置', '缺损', '处', 1, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (14, '桥面系', '桥面系', '伸缩缝装置', '阻塞', '处', 1, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (15, '桥面系', '桥面系', '泄水孔', '泄水孔', '处', 1, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (16, '上部结构', '上部结构', '上部结构', '主梁(整体完好情况、振动)', NULL, 1, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (17, '上部结构', '上部结构', '上部结构', '横向联系', NULL, 1, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (18, '上部结构', '上部结构', '上部结构', '拱肋(拱脚区、钢管节点)', NULL, 1, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (19, '上部结构', '上部结构', '上部结构', '吊杆(上下锚头、振动)', NULL, 1, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (20, '上部结构', '上部结构', '上部结构', '上部其他变异', NULL, 1, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (21, '台/墩/附属物', '桥墩、桥台、附属物', '桥墩、桥台、附属物', '桥墩/桥台', NULL, 1, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (22, '台/墩/附属物', '桥墩、桥台、附属物', '桥墩、桥台、附属物', '锥坡', NULL, 1, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (23, '台/墩/附属物', '桥墩、桥台、附属物', '桥墩、桥台、附属物', '下部其他变异', NULL, 1, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (24, '施工', '桥、桥区施工', '桥、桥区施工', '桥、桥区施工', NULL, 1, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (25, '其他病害因素', '其他危及行车、行船、行人安全的病害因素', '其他危及行车、行船、行人安全的病害因素', '其他危及行车、行船、行人安全的病害因素', NULL, 1, 2);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (26, '其它说明', '其它说明', '其它说明', '其它说明', NULL, 1, 3);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (27, '洞口', '洞口', '洞口', '边坡危石', '处', 2, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (28, '洞口', '洞口', '洞口', '边坡积水', '处', 2, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (29, '洞口', '洞口', '洞口', '边沟淤塞', '处', 2, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (30, '洞口', '洞口', '洞口', '开裂', '处', 2, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (31, '洞口', '洞口', '洞口', '倾斜', '处', 2, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (32, '洞口', '洞口', '洞口', '沉陷', '处', 2, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (33, '洞门', '洞门', '洞门', '开裂', '处', 2, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (34, '洞门', '洞门', '洞门', '倾斜', '处', 2, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (35, '洞门', '洞门', '洞门', '沉陷', '处', 2, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (36, '洞门', '洞门', '洞门', '错台', '处', 2, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (37, '洞门', '洞门', '洞门', '起层', '处', 2, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (38, '洞门', '洞门', '洞门', '剥落', '处', 2, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (39, '洞门', '洞门', '洞门', '渗漏水', '处', 2, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (40, '衬砌', '衬砌', '衬砌', '裂纹', '处', 2, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (41, '衬砌', '衬砌', '衬砌', '错台', '处', 2, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (42, '衬砌', '衬砌', '衬砌', '起层', '处', 2, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (43, '衬砌', '衬砌', '衬砌', '剥落', '处', 2, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (44, '衬砌', '衬砌', '衬砌', '渗漏水', '处', 2, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (45, '路面', '路面', '路面', '
落物', '处', 2, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (46, '路面', '路面', '路面', '油污', '处', 2, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (47, '路面', '路面', '路面', '滞水', '处', 2, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (48, '路面', '路面', '路面', '路面拱起', '处', 2, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (49, '路面', '路面', '路面', '坑槽', '处', 2, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (50, '路面', '路面', '路面', '开裂', '处', 2, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (51, '路面', '路面', '路面', '错台', '处', 2, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (52, '检修道', '检修道', '检修道', '结构破损', '处', 2, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (53, '检修道', '检修道', '检修道', '盖板缺损', '处', 2, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (54, '排水设施', '排水设施', '排水设施', '缺损', '处', 2, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (55, '排水设施', '排水设施', '排水设施', '堵塞', '处', 2, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (56, '排水设施', '排水设施', '排水设施', '积水', '处', 2, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (57, '吊顶/预埋件', '吊顶及各种预埋件', '吊顶及各种预埋件', '变形', '处', 2, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (58, '吊顶/预埋件', '吊顶及各种预埋件', '吊顶及各种预埋件', '缺损', '处', 2, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (59, '吊顶/预埋件', '吊顶及各种预埋件', '吊顶及各种预埋件', '漏水', '处', 2, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (60, '内饰', '内饰', '内饰', '脏污', '处', 2, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (61, '内饰', '内饰', '内饰', '变形', '处', 2, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (62, '内饰', '内饰', '内饰', '缺损', '处', 2, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (63, '标志标线轮廓标', '各种标志标线轮廓标', '各种标志标线轮廓标', '各种标志标线轮廓标', '处', 2, 1);
INSERT INTO "public"."tb_inspection_disease"("id", "name", "disease_part", "check_item", "damage_type", "unit", "structure_type", "type") VALUES (64, '其它说明', '其它说明', '其它说明', '其它说明', NULL, 2, 3);

--巡查病害选项表
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (1, 1, '完整', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (2, 1, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (3, 2, '完整', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (4, 2, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (5, 3, '完好', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (6, 3, '碎裂', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (7, 4, '完好', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (8, 4, '坑槽', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (9, 5, '平整', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (10, 5, '拥包', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (11, 6, '平整', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (12, 6, '车辙', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (13, 7, '平顺', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (14, 7, '跳车', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (15, 8, '完整', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (16, 8, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (17, 9, '完整', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (18, 9, '破损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (19, 10, '平整', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (20, 10, '坑塘', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (21, 11, '完整', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (22, 11, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (23, 12, '完整', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (24, 12, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (25, 13, '完整', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (26, 13, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (27, 14, '正常', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (28, 14, '阻塞', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (29, 15, '通畅', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (30, 15, '阻塞', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (31, 16, '正常', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (32, 16, '异常', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (33, 17, '正常', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (34, 17, '异常', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (35, 18, '正常', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (36, 18, '异常', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (37, 19, '正常', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (38, 19, '异常', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (39, 20, '正常', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (40, 20, '异常', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (41, 21, '正常', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (42, 21, '异常', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (43, 22, '正常', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (44, 22, '异常', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (45, 23, '正常', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (46, 23, '异常', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (47, 25, '桥面落物', 1, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (48, 25, '电线管道破损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (49, 25, '车辆事故', 3, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (50, 25, '车辆违规停放', 4, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (51, 24, '异常', 1, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (52, 24, '正常', 2, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (66, 27, '完好', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (67, 27, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (68, 28, '完好', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (69, 28, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (70, 29, '完好', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (71, 29, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (72, 30, '完好', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (73, 30, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (74, 31, '完好', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (75, 31, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (76, 32, '完好', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (77, 32, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (78, 33, '完好', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (79, 33, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (80, 34, '完好', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (81, 34, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (82, 35, '完好', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (83, 35, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (84, 36, '完好', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (85, 36, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (86, 37, '完好', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (87, 37, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (88, 38, '完好', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (89, 38, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (90, 39, '完好', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (91, 39, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (92, 40, '完好', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (93, 40, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (94, 41, '完好', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (95, 41, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (96, 42, '完好', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (97, 42, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (98, 43, '完好', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (99, 43, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (100, 44, '完好', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (101, 44, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (102, 45, '完好', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (103, 45, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (104, 46, '完好', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (105, 46, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (106, 47, '完好', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (107, 47, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (108, 48, '完好', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (109, 48, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (110, 49, '完好', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (111, 49, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (112, 50, '完好', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (113, 50, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (114, 51, '完好', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (115, 51, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (116, 52, '完好', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (117, 52, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (118, 53, '完好', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (119, 53, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (120, 54, '完好', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (121, 54, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (122, 55, '完好', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (123, 55, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (124, 56, '完好', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (125, 56, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (126, 57, '完好', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (127, 57, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (128, 58, '完好', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (129, 58, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (130, 59, '完好', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (131, 59, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (132, 60, '完好', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (133, 60, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (134, 61, '完好', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (135, 61, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (136, 62, '完好', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (137, 62, '缺损', 2, 0);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (138, 63, '完好', 1, 1);
INSERT INTO "public"."tb_inspection_disease_option"("id", "inspection_disease_id", "name", "seq_num", "option_status") VALUES (139, 63, '缺损', 2, 0);

