server:
  port: 9990
  context-path: /bridge
  session:
    timeout: 4200
  tomcat:
    uri-encoding: UTF-8
    max-connections: 200
    max-threads: 300
    accept-count: 100
    basedir: /home/temp #改变临时文件位置

multipart:
  enabled: true
  maxFileSize: 1024Mb
  maxRequestSize: 1024Mb

security:
  basic:
    enabled: false
  user:
    name: admin
    password: admin

mybatis:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.iware.bridge.dto

spring:
  profiles:
    active: dev
  application:
    name: bridge

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  http:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB

  jpa:
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

pagehelper:
  helper-dialect: PostgreSQL
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

remote:
  maxTotalConnect: 0
  maxConnectPerRoute: 200
  connectTimeout: 2000
  readTimeout: 3000

info:
    name: ${spring.application.name}
    description: 桥梁
    environment: ${spring.profiles.active}
    version: 1.3.1
